INSERT INTO TABLE_ONE (SOME_STRING, SOME_INTEGER, SOME_INDEX, SOME_DATA) VALUES ('foobar', 1337, 1, 'someData');
INSERT INTO TABLE_ONE (SOME_STRING, SOME_INTEGER, SOME_INDEX, SOME_DATA) VALUES ('foobar', 1337, 2, 'someData');
INSERT INTO TABLE_ONE (SOME_STRING, SOME_INTEGER, SOME_INDEX, SOME_DATA) VALUES ('foobar', 1337, 3, 'someData');
INSERT INTO TABLE_TWO (SOME_STRING, SOME_INTEGER, SOME_INDEX, SOME_DATA) VALUES ('foobar', 1337, 2, 'irrelevantData');
