CREATE TABLE TABLE_ONE (SOME_STRING VARCHAR(32), SOME_INTEGER INTEGER, SOME_INDEX INTEGER, SOME_DATA VARCHAR(256));
CREATE TABLE TABLE_TWO (SOME_STRING VARCHAR(32), SOME_INTEGER INTEGER, SOME_INDEX INTEGER, SOME_DATA VARCHAR(256));
